In [2]:
from typing import List
import numpy as np

### Задача 1. «Треугольник с максимальным периметром»
Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрез
ков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью функция возвращает 0.

In [3]:
def triangle(array:List[int]) -> int:
    if len(array) < 3:
        return 0
    
    array.sort()
    array.reverse()

    for i in range(len(array) - 2):
        if array[i + 1] + array[i + 2] > array[i]:
            return array[i + 1] + array[i + 2] + array[i]
    
    return 0

print(triangle([2, 1, 2]))
print(triangle([1, 2, 1]))
print(triangle([3, 2, 3, 4]))
print(triangle([3, 6, 2, 3]))

5
0
10
8


### Задача 2. «Максимальное число»
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

Замечание: Результат может быть очень большим числом, поэтому представьте его как
string, а не integer.

In [39]:
def largest_num(array:List[int]) -> str:
    if len(array) == 1:
        return str(array[0])
    
    array = list(map(str, array))
    
    for i in range(len(array)):
        for j in range(1+i,len(array)):
            if array[j]+array[i]>array[i]+array[j]:
                array[i],array[j]=array[j],array[i]

    result=''.join(array)

    if(set(result) == '0'):
        return '0'
    
    else:
        return result
    
largest_num([3,30,34,5,9])
    

'9534330'

### Задача 3. «Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сор
тирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся мат
рицу.

In [40]:
def mat_sort(mat:List[List[int]]) -> List[List[int]]:
    m = len(mat)
    n = len(mat[0])
    arr = sorted(np.array(mat).flatten().tolist())
    ans = np.reshape([0] * n * m, (m, n))
    i=0
    j=0
    l = 0
    count = 0


    while i + j < n + m:
        k = j
        
        while k < n:
            ans[i][k] = arr[count]
            count += 1
            k += 1
        
        l = i + 1

        while l < m:
            ans[l][j] = arr[count]
            l += 1
            count += 1
        
        i += 1
        j += 1

        if i == m or j == n:
            break

    print(ans)
    


matrix = [[11, 25, 66, 1, 69, 7], [23, 55, 17, 45, 15, 52], [75, 31, 36,44, 58, 8], [22, 27, 33, 25, 68, 4], [84, 28, 14, 11, 5, 50]]
mat_sort(matrix)

[[ 1  4  5  7  8 11]
 [11 22 23 25 25 27]
 [14 28 36 44 45 50]
 [15 31 52 58 66 68]
 [17 33 55 69 75 84]]
