In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

path = "..\\img\\photo_2023-07-31_23-02-41.jpg"

# [Basic Operations on Images](https://docs.opencv.org/4.10.0/d3/df2/tutorial_py_basic_ops.html)

In [2]:
img = cv.imread(path)
assert img is not None, "file could not be read, check with os.path.exists()"

In [3]:
px = img[100, 100]
print(px)

blue = img[100, 100, 0]
print(blue)

img[100, 100] = [255, 255, 255]
print(img[100, 100])

[197 214 233]
197
[255 255 255]


In [4]:
img.item(10, 10, 2)


238

In [5]:
img[(10, 10, 2)] = 100
img.item(10, 10, 2)

100

In [6]:
print(img.shape)
print(img.size)
print(img.dtype)

(980, 802, 3)
2357880
uint8


In [7]:
ball = img[280:340, 330:390]
img[273:333, 100:160] = ball
cv.imshow("Display window", img)
k = cv.waitKey(0)

In [8]:
b, g, r = cv.split(img)
img = cv.merge((b, g, r))

# b = img[:,:,0]

In [ ]:
BLUE = [255, 0, 0]

img1 = cv.imread(path)
assert img1 is not None, "file could not be read, check with os.path.exists()"

replicate = cv.copyMakeBorder(img1, 50, 50, 50, 50, cv.BORDER_REPLICATE)
reflect = cv.copyMakeBorder(img1, 50, 50, 50, 50, cv.BORDER_REFLECT)
reflect101 = cv.copyMakeBorder(img1, 50, 50, 50, 50, cv.BORDER_REFLECT_101)
wrap = cv.copyMakeBorder(img1, 50, 50, 50, 50, cv.BORDER_WRAP)
constant = cv.copyMakeBorder(img1, 50, 50, 50, 50, cv.BORDER_CONSTANT, value=BLUE)

plt.subplot(231), plt.imshow(img1, "gray"), plt.title("ORIGINAL")
plt.subplot(232), plt.imshow(replicate, "gray"), plt.title("REPLICATE")
plt.subplot(233), plt.imshow(reflect, "gray"), plt.title("REFLECT")
plt.subplot(234), plt.imshow(reflect101, "gray"), plt.title("REFLECT_101")
plt.subplot(235), plt.imshow(wrap, "gray"), plt.title("WRAP")
plt.subplot(236), plt.imshow(constant, "gray"), plt.title("CONSTANT")

plt.show()

# [Arithmetic Operations on Images](https://docs.opencv.org/4.10.0/d0/d86/tutorial_py_image_arithmetics.html)

In [10]:
x = np.uint8([250])
y = np.uint8([10])

print(cv.add(x, y))  # 250+10 = 260 => 255
print(x + y)  # 250+10 = 260 % 256 = 4

[[260.]
 [  0.]
 [  0.]
 [  0.]]
[4]


In [11]:
img1 = cv.imread(path)
img2 = cv.imread("..\\img\\sponge.jpg")
assert img1 is not None, "file could not be read, check with os.path.exists()"
assert img2 is not None, "file could not be read, check with os.path.exists()"


down_width, down_height, _ = img2.shape
down_points = (down_width, down_height)
img1 = cv.resize(img1, down_points, interpolation=cv.INTER_LINEAR)

dst = cv.addWeighted(img1, 0.7, img2, 0.3, 0)

cv.imshow("dst", dst)
cv.waitKey(0)
cv.destroyAllWindows()

In [13]:
img1 = cv.imread(path)
img2 = cv.imread("..\\img\\sponge.jpg")
assert img1 is not None, "file could not be read, check with os.path.exists()"
assert img2 is not None, "file could not be read, check with os.path.exists()"

down_width, down_height, _ = img2.shape
down_points = (down_width, down_height)
img1 = cv.resize(img1, down_points, interpolation=cv.INTER_LINEAR)

# I want to put logo on top-left corner, So I create a ROI
rows, cols, channels = img2.shape
roi = img1[0:rows, 0:cols]

# Now create a mask of logo and create its inverse mask also
img2gray = cv.cvtColor(img2, cv.COLOR_BGR2GRAY)
ret, mask = cv.threshold(img2gray, 100, 255, cv.THRESH_BINARY)
mask_inv = cv.bitwise_not(mask)

# Now black-out the area of logo in ROI
img1_bg = cv.bitwise_and(roi, roi, mask=mask_inv)

# Take only region of logo from logo image.
img2_fg = cv.bitwise_and(img2, img2, mask=mask)

# Put logo in ROI and modify the main image
dst = cv.add(img1_bg, img2_fg)
img1[0:rows, 0:cols] = dst

cv.imshow("res", img1)
cv.waitKey(0)
cv.destroyAllWindows()

# [Geometric Transformations of Images](https://docs.opencv.org/4.10.0/da/d6e/tutorial_py_geometric_transformations.html)

In [ ]:
img = cv.imread(path)
assert img1 is not None, "file could not be read, check with os.path.exists()"

res = cv.resize(img, None, fx=2, fy=2, interpolation=cv.INTER_CUBIC)

# OR

# height, width = img.shape[:2]
# res = cv.resize(img,(2*width, 2*height), interpolation = cv.INTER_CUBIC)
fig, ax = plt.subplots(nrows=1, ncols=2)
ax[0].imshow(img)
ax[1].imshow(res)

In [15]:
img = cv.imread(path, cv.IMREAD_GRAYSCALE)
assert img is not None, "file could not be read, check with os.path.exists()"
rows, cols = img.shape

M = np.float32([[1, 0, 100], [0, 1, 50]])
dst = cv.warpAffine(img, M, (cols, rows))

cv.imshow("img", dst)
cv.waitKey(0)
cv.destroyAllWindows()

In [ ]:
img = cv.imread(path, cv.IMREAD_GRAYSCALE)
assert img is not None, "file could not be read, check with os.path.exists()"
rows, cols = img.shape

# cols-1 and rows-1 are the coordinate limits.
M = cv.getRotationMatrix2D(((cols - 1) / 2.0, (rows - 1) / 2.0), 90, 1)
dst = cv.warpAffine(img, M, (cols, rows))

fig, ax = plt.subplots(nrows=1, ncols=2)
ax[0].imshow(img, cmap="gray")
ax[1].imshow(dst, cmap="gray")

In [ ]:
img = cv.imread(path)
assert img is not None, "file could not be read, check with os.path.exists()"
rows, cols, ch = img.shape

pts1 = np.float32([[50, 50], [200, 50], [50, 200]])
pts2 = np.float32([[10, 100], [200, 50], [100, 250]])

M = cv.getAffineTransform(pts1, pts2)

dst = cv.warpAffine(img, M, (cols, rows))

plt.subplot(121), plt.imshow(img), plt.title("Input")
plt.subplot(122), plt.imshow(dst), plt.title("Output")
plt.show()

In [ ]:
img = cv.imread(path)
assert img is not None, "file could not be read, check with os.path.exists()"
rows, cols, ch = img.shape

pts1 = np.float32([[56, 65], [368, 52], [28, 387], [389, 390]])
pts2 = np.float32([[0, 0], [300, 0], [0, 300], [300, 300]])

M = cv.getPerspectiveTransform(pts1, pts2)

dst = cv.warpPerspective(img, M, (300, 300))

plt.subplot(121), plt.imshow(img), plt.title("Input")
plt.subplot(122), plt.imshow(dst), plt.title("Output")
plt.show()